config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => { :registrations => "custom/registrations" }

  match '/contact_forms/new', to: 'contact_forms#new', via: 'get'
  resources "contact_forms", only: [:new, :create]
  root to: "home#index"

  resource :user, only: [:show] do
    resource :profiles, path: "profile", except: [:index, :show, :delete]
  end

  get '/users', to: redirect('/users/sign_up')

  get '/user/grants', to: 'grants#usergrants', as: 'user_grants'

  post '/user/card', to: 'users#create_card', as: 'create_card'

  delete '/user/card', to: 'users#delete_card', as: 'delete_card'

  post '/user/card/edit', to: 'users#edit_card', as: 'edit_card'

  resources :grants do
    resources :payments, except: [:index]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_many :grants, dependent: :destroy
  belongs_to :school
  validates :first_name, :last_name, :email, :role, presence: true
  before_save :format_name


  enum role: {"friends_and_family" => 0, "teacher" => 1}

  def full_name
    first_name + " " + last_name
  end

  private

  def format_name
    self.first_name = self.first_name.capitalize
    self.last_name = self.last_name.capitalize
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_next

  def show
    if params['current']
      @current_tab = "##{params['current']}"
    end
    @profile = current_user.profile
    @payments = current_user.payments
    @school = current_user.school
    Stripe.api_key = ENV['stripe_api_key']
    @customer = nil
    if current_user.stripe_token?
      @customer = Stripe::Customer.retrieve(current_user.stripe_token)
    end
  end

  def create_card
    Stripe.api_key = ENV['stripe_api_key']
    begin
      tok = Stripe::Token.retrieve(params[:card_token])
      if !current_user.stripe_token?
        customer = Stripe::Customer.create({
          email: current_user.email,
          source: tok,
        })
        current_user.stripe_token = customer.id
        current_user.save
      else
        customer = Stripe::Customer.retrieve(current_user.stripe_token)
        card = customer.sources.create({source: tok})
        if params[:default]
          customer.default_source = card.id
          customer.save
        end
      end
      if params[:next]
        redirect_to params[:next], notice: 'Successfully created card'
      else
        redirect_to user_path + "?current=credit-card-label", notice: 'Successfully created card'
      end
    rescue => e
      redirect_to user_path + "?current=credit-card-label", alert: 'Could not find token to create card'
    end
  end

  def edit_card
    Stripe.api_key = ENV['stripe_api_key']
    customer = Stripe::Customer.retrieve(current_user.stripe_token)
    card_found = false
    customer.sources.each do |card|
      if card.id.include?(params[:card_id])
        card_found = true
        card_params.keys.each do |key|
          unless card_params[key].empty?
            card[key] = card_params[key]
          end
        end
        begin
          card.save
          if params[:default]
            customer.default_source = card.id
            customer.save
          end
          if params[:next]
            redirect_to params[:next], notice: 'Successfully updated card'
          else
            redirect_to user_path + "?current=credit-card-label", notice: 'Successfully updated card'
          end
        rescue => e
          p e
          redirect_to user_path + "?current=credit-card-label", alert: 'Could not update card'
        end
        break
      end
    end
    redirect_to user_path + "?current=credit-card-label", alert: 'Could not find card' unless card_found
  end

  def delete_card
    Stripe.api_key = ENV['stripe_api_key']
    customer = Stripe::Customer.retrieve(current_user.stripe_token)
    card_found = false
    customer.sources.each do |card|
      if card.id.include?(params[:card_id])
        card_found = true
        begin
          card.delete
          redirect_to user_path + "?current=credit-card-label", notice: 'Successfully deleted card'
        rescue => e
          p e
          redirect_to user_path + "?current=credit-card-label", alert: 'Could not delete card'
        end
      end
    end
    redirect_to user_path + "?current=credit-card-label", alert: 'Could not find card' unless card_found
  end

  private

  def card_params
    params.permit(:name, :exp_month, :exp_year, :address_city, :address_state, :address_zip, :address_line1, :address_line2, :address_country)
  end

  def set_next
    @next = session[:next] if session[:next]
    session[:next] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_card.html.erb
<%= form_tag edit_card_path do %>
  <div class="row">
    <div class="input column small-6">
      <%= label_tag :name, "Cardholder Name" %>
      <%= text_field_tag :name, card.name  %>
    </div>
  </div>
  <div class="row">
    <div class="input column small-2">
      <%= label_tag :exp_month %>
      <%= select_tag :exp_month, options_for_select(1..12, card.exp_month) %>
    </div>
    <div class="input column small-2">
      <%= label_tag :exp_year %>
      <%= select_tag :exp_year, options_for_select(Time.now.to_date.year..Time.now.to_date.year+20, card.exp_year) %>
    </div>
  </div>
  <h3 class="billing">Billing Address</h3>
  <div class="row">
    <div class="input column small-12">
      <%= label_tag :address_line1, "Address Line 1" %>
      <%= text_field_tag :address_line1, card.address_line1 %>
    </div>
  </div>
  <div class="row">
    <div class="input column small-12">
      <%= label_tag :address_line2, "Address Line 2" %>
      <%= text_field_tag :address_line2, card.address_line2 %>
    </div>
  </div>
  <div class="row">
    <div class="input column small-5">
      <%= label_tag :address_city, "City" %>
      <%= text_field_tag :address_city, card.address_city %>
    </div>
    <div class="input column small-2">
      <%= label_tag :address_state, "State" %>
      <%= select_tag :address_state, options_for_select(us_states, card.address_state) %>
    </div>
    <div class="input column small-2">
      <%= label_tag :address_zip, "Zip Code" %>
      <%= text_field_tag :address_zip, card.address_zip %>
    </div>
    <%= hidden_field_tag :card_id, card.id[(card.id.length/2)..-1], class: "card-id" %>
  </div>
  <div style="text-align: center;">
    <%= label_tag :default, "Use as default payment method?" %>
    <%= check_box_tag :default %>
  </div>
  <% if @next %>
    <input type="hidden" name="next" value="<%= @next%>">
  <% end %>
  <%= submit_tag "Save", class: "button warning" %>
  <div class="button warning cancel-edit">Cancel</div>
<% end %>

app/views/users/_horizontal.html.erb
<ul class="tabs block-width" data-tabs data-match-height="true" id="account-tabs">
  <li class="tabs-title is-active blocked"><a class="text-center" href="#user-profile" aria-selected="true">Profile</a></li>
  <li class="tabs-title blocked"><a class="text-center" href="#account">Account Settings</a></li>
  <li class="tabs-title blocked"><a class="text-center" href="#payment">Payment History</a></li>
  <li class="tabs-title blocked"><a class="text-center" href="#credit-card">Payment Settings</a></li>
</ul>

<div class="tabs-content" data-tabs-content="account-tabs">
  <div class="tabs-panel is-active" id="user-profile">
    <div class="row">
      <% if !current_user.profile %>
        <div class="float-center">
          <%= button_to "Create Profile", new_user_profiles_path, method: "get", class: "button warning" %>
        </div>
      <% else %>
        <% if current_user.role == "teacher" %>
          <div class="columns small-6">
            <p class="text-right">About:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.about %></p>
          </div>
          <div class="columns small-6">
            <p class="text-right">Grade you teach:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.grade %></p>
          </div>
          <div class="columns small-6">
            <p class="text-right">Teacher Since:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.started_teaching %></p>
          </div>
          <div class="columns small-6">
            <p class="text-right">Work Phone:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.work_phone %></p>
          </div>
        <% end %>

        <div class="columns small-6">
          <p class="text-right">Home Phone:</p>
        </div>
        <div class="user-attribute-values columns small-6">
          <p><%= @profile.home_phone %></p>
        </div>
        <div class="columns small-6">
          <p class="text-right">Address:</p>
        </div>
        <div class="user-attribute-values columns small-6">
          <p><%= @profile.address %></p>
        </div>
        <div class="columns small-6">
          <p class="text-right">City:</p>
        </div>
        <div class="user-attribute-values columns small-6">
          <p><%= @profile.city %></p>
        </div>
        <div class="columns small-6">
          <p class="text-right">State:</p>
        </div>
        <div class="user-attribute-values columns small-6">
          <p><%= @profile.state %></p>
        </div>
        <div class="columns small-6">
          <p class="text-right">Zip:</p>
        </div>
        <div class="user-attribute-values columns small-6">
          <p><%= @profile.zipcode %></p>
        </div>
      <% end %>
    </div>
    <% if current_user.profile %>
      <div class="columns small-12">
        <%= button_to "Edit Profile", edit_user_profiles_path, class: "button warning float-center", method: "get" %>
      </div>
    <% end %>
  </div>
  <div class="tabs-panel" id="account">
    <div class="row">
      <div class="user-attributes small-6">
        <p class="text-right">First Name:</p>
        <p class="text-right">Last Name:</p>
        <p class="text-right">Email:</p>
        <% if current_user.role == "teacher" %>
          <p class="text-right">Relationship:</p>
        <% end %>
      </div>
      <div class="user-attribute-values small-6">
        <p> <%= current_user.first_name %> </p>
        <p> <%= current_user.last_name %> </p>
        <p> <%= current_user.email %> </p>
        <% if current_user.role == "teacher" %>
          <p> <%= current_user.role %> </p>
        <% end %>
      </div>
    </div>
    <div class="columns small-12">
      <%= button_to "Edit Account Settings", edit_user_registration_path, class: "button warning float-center", method: "get" %>
    </div>
  </div>
  <div class="tabs-panel" id="payment">
    <div class="row">
      <% if @payments.length == 0 %>
        <h4 class="float-center">You have not pledged to any grants.</h4>
      <% else %>
      <table>
        <thead>
          <tr>
            <th>Pledged On:</th>
            <th>Amount:</th>
            <th>Grant Name</th>
            <th>Grant Status</th>
            <th>Payment Status</th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.created_at.strftime('%B %d, %Y') %></td>
            <td>$<%= payment.amount %></td>
            <td><%= link_to payment.grant.title, grant_path(payment.grant) %></td>
            <td><%= payment.grant.status %></td>
            <td><%= payment.status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
  <div class="tabs-panel" id="credit-card">
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Default</th>
            <th>Provider</th>
            <th>Name On Card</th>
            <th>Last Four</th>
            <th>Exp. Date</th>
            <th>Card Type</th>
            <th>Billing Address</th>
            <th>Edit Card</th>
            <th>Delete Card</th>
          </tr>
        </thead>
        <tbody>
          <% if @customer %>
            <% @customer.sources.each_with_index do |card, index| %>
              <tr id="card<%= index %>">
                <td style="text-align: center;">
                  <% if card.id == @customer.default_source %>
                    <span class="badge success"><%= fa_icon "check" %></span>
                  <% end %>
                </td>
                <td>
                  <% case card.brand %>
                  <% when "Visa" %>
                    <%= image_tag "logo-visa.jpg", class: "brand-img" %>
                  <% when "MasterCard" %>
                    <%= image_tag "logo-mastercard.jpg", class: "brand-img" %>
                  <% when "American Express" %>
                    <%= image_tag "logo-americanExpress.jpg", class: "brand-img" %>
                  <% when "Discover" %>
                    <%= image_tag "logo-discover.jpg", class: "brand-img" %>
                  <% else %>
                    <%= card.brand %>
                  <% end %>
                </td>
                <td><%= card.name %></td>
                <td><%= card.last4 %></td>
                <td><%= Date.new(card.exp_year, card.exp_month).strftime('%B %Y') %></td>
                <td><%= card.funding %></td>
                <td>
                  <% if (card.address_line1 and !card.address_line1.empty?) %>
                    <%=  "#{card.address_line1}  #{card.address_line2} #{card.address_city}, #{card.address_state}, #{card.address_zip}" %>
                  <% end %>
                </td>
                <td style="text-align: center;"><span class="badge click warning"><%= fa_icon "pencil", style: "color: white;"%></span></td>
                <td style="text-align: center;">
                  <% if @customer.sources.data.length == 1 and !current_user.payments.where(status: 0).empty? %>
                    <span data-tooltip aria-haspopup="true" class="has-tip badge secondary" title="You have a donation pledge pending, another card must be added before this one can be deleted"><%= fa_icon "times" %></i></span>
                  <% else %>
                    <%= form_tag delete_card_path, method: 'delete' do %>
                      <%= hidden_field_tag :card_id %>
                      <span class="badge click alert"><%= fa_icon "times" %></i></span>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="button warning new-card">Add Card</div>
      <%= render "new_card"%>
      <% if @customer %>
        <% @customer.sources.each_with_index do |card, index| %>
          <div class="edit-card-form card<%= index %>" style="width: 100%; display: none;">
            <%= render "edit_card", card: card %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_new_card.html.erb
<div class="new-card-form" style="width: 100%;">
  <%= form_tag create_card_path do %>
    <div class="form-inputs">
      <div class="row">
        <div class="input column small-6">
          <%= label_tag :name, "Cardholder Name" %>
          <%= text_field_tag :name %>
        </div>
      </div>
      <label>Card Information</label>
      <div class="card-element"></div>

      <h3 class="billing">Billing Address</h3>
      <div class="row">
        <div class="input column small-12">
          <%= label_tag :address_line1, "Address Line 1" %>
          <%= text_field_tag :address_line1 %>
        </div>
      </div>
      <div class="row">
        <div class="input column small-12">
          <%= label_tag :address_line2, "Address Line 2" %>
          <%= text_field_tag :address_line2 %>
        </div>
      </div>
      <div class="row">
        <div class="input column small-5">
          <%= label_tag :address_city, "City" %>
          <%= text_field_tag :address_city %>
        </div>
        <div class="input column small-3">
          <%= label_tag :address_state, "State" %>
          <%= select_tag :address_state, options_for_select(us_states) %>
        </div>
        <div class="input column small-4">
          <%= label_tag :address_country, "Country" %>
          <%= render "country_select" %>
        </div>
      </div>
      <%= hidden_field_tag :card_token %>
      <div style="text-align: center;">
        <%= label_tag :default, "Use as default payment method?" %>
        <%= check_box_tag :default %>
      </div>
      <% if @next %>
        <input type="hidden" name="next" value="<%= @next%>">
      <% end %>
      <%= submit_tag "Save", class: "card-submit button warning" %>
      <div class="button warning cancel-edit">Cancel</div>
    </div>
  <% end %>
</div>

app/views/users/_vertical.html.erb
<ul class="tabs" data-responsive-accordion-tabs="tabs small-accordion" data-allow-all-closed="true" data-match-height="true" id="account-tabs-v">
  <li class="tabs-title"><a class="text-center" href="#user-profile-v" aria-selected="true">Profile</a></li>
  <li class="tabs-title"><a class="text-center" href="#account-v">Account Settings</a></li>
  <li class="tabs-title"><a class="text-center" href="#payment-v">Payment History</a></li>
  <li class="tabs-title"><a class="text-center" href="#credit-card-v">Payment Settings</a></li>
</ul>

<div class="tabs-content" data-tabs-content="account-tabs-v">
  <div class="tabs-panel" id="user-profile-v">
    <div class="row">
      <% if !current_user.profile %>
        <div class="float-center">
          <%= button_to "Create Profile", new_user_profiles_path, method: "get", class: "button warning" %>
        </div>
      <% else %>
      <% if current_user.role == "teacher" %>

          <div class="columns small-6">
            <p class="text-right">About:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.about %></p>
          </div>

          <div class="columns small-6">
            <p class="text-right">Grade you teach:</p>
          </div>
          <div class="user-attribute-values columns small-6">
            <p><%= @profile.grade %></p>
          </div>

          <div class="columns small-6">
            <p class="text-right">Teacher Since:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.started_teaching %></p>
          </div>

          <div class="columns small-6">
            <p class="text-right">Work Phone:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.work_phone %></p>
          </div>

          <% end %>

          <div class="columns small-6">
          <p class="text-right">Home Phone:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.home_phone %></p>
          </div>

          <div class="columns small-6">
          <p class="text-right">Address:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.address %></p>
          </div>

          <div class="columns small-6">
          <p class="text-right">City:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.city %></p>
          </div>

          <div class="columns small-6">
          <p class="text-right">State:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.state %></p>
          </div>

          <div class="columns small-6">
          <p class="text-right">Zip:</p>
          </div>
          <div class="user-attribute-values columns small-6">
          <p><%= @profile.zipcode %></p>
          </div>
      <% end %>
    </div>
    <% if current_user.profile %>
      <div class="columns small-12">
        <%= button_to "Edit Profile", edit_user_profiles_path, class: "button warning float-center", method: "get" %>
      </div>
    <% end %>
  </div>
  <div class="tabs-panel" id="account-v">
    <div class="row">
      <div class="user-attributes small-6">
        <p class="text-right">First Name:</p>
        <p class="text-right">Last Name:</p>
        <p class="text-right">Email:</p>
        <p class="text-right">Relationship:</p>
      </div>
      <div class="user-attribute-values small-6">
        <p> <%= current_user.first_name %> </p>
        <p> <%= current_user.last_name %> </p>
        <p> <%= current_user.email %> </p>
        <p> <%= current_user.role %> </p>
      </div>
    </div>
    <div class="columns small-12">
      <%= button_to "Edit Account Settings", edit_user_registration_path, class: "button warning float-center", method: "get" %>
    </div>
  </div>
  <div class="tabs-panel" id="payment-v">
    <div class="row">
      <% if @payments.length == 0 %>
        <h4 class="float-center">You have not pledged to any grants.</h4>
      <% else %>
      <table>
        <thead>
          <tr>
            <th>Pledged On:</th>
            <th>Amount:</th>
            <th>Grant Name</th>
            <th>Grant Status</th>
            <th>Payment Status</th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.created_at.strftime('%B %d, %Y') %></td>
            <td>$<%= payment.amount %></td>
            <td><%= link_to payment.grant.title, grant_path(payment.grant) %></td>
            <td><%= payment.grant.status %></td>
            <td><%= payment.status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
  <div class="tabs-panel" id="credit-card-v">
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Default</th>
            <th>Name On Card</th>
            <th>Last Four</th>
            <th>Expiration Date</th>
            <th>Edit Card</th>
            <th>Delete Card</th>
          </tr>
        </thead>
        <tbody>
          <% if @customer %>
            <% @customer.sources.each_with_index do |card, index| %>
              <tr id="card<%= index %>">
                <td style="text-align: center;">
                  <% if card.id == @customer.default_source %>
                    <span class="badge success"><%= fa_icon "check" %></span>
                  <% end %>
                </td>
                <td><%= card.name %></td>
                <td><%= card.last4 %></td>
                <td><%= Date.new(card.exp_year, card.exp_month).strftime('%B %Y') %></td>
                <td style="text-align: center;"><span class="badge click warning"><%= fa_icon "pencil", style: "color: white;"%></span></td>
                <td style="text-align: center;">
                  <% if card.id == @customer.default_source %>
                    <span class="badge secondary"><%= fa_icon "times" %></i></span>
                  <% else %>
                    <%= form_tag delete_card_path, method: 'delete' do %>
                      <%= hidden_field_tag :card_id %>
                      <span class="badge click alert"><%= fa_icon "times" %></i></span>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="button warning new-card">Add Card</div>
      <%= render "new_card"%>
      <% if @customer %>
        <% @customer.sources.each_with_index do |card, index| %>
          <div class="edit-card-form card<%= index %>" style="width: 100%; display: none;">
            <%= render "edit_card", card: card %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2 style="text-align: center"><%= current_user.first_name%> <%= current_user.last_name%></h2>

<p hidden id="current-tab">
  <% if @current_tab %>
    <%= @current_tab %>
  <% else %>
    #user-profile-label
  <% end -%>
</p>

<div class="show-for-medium">
  <%= render "horizontal" %>
</div>

<div class="show-for-small-only">
  <%= render "vertical" %>
</div>