config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => { :registrations => "custom/registrations" }

  match '/contact_forms/new', to: 'contact_forms#new', via: 'get'
  resources "contact_forms", only: [:new, :create]
  root to: "home#index"

  resource :user, only: [:show] do
    resource :profiles, path: "profile", except: [:index, :show, :delete]
  end

  get '/users', to: redirect('/users/sign_up')

  get '/user/grants', to: 'grants#usergrants', as: 'user_grants'

  post '/user/card', to: 'users#create_card', as: 'create_card'

  delete '/user/card', to: 'users#delete_card', as: 'delete_card'

  post '/user/card/edit', to: 'users#edit_card', as: 'edit_card'

  resources :grants do
    resources :payments, except: [:index]
  end

end

app/views/shared/_about.html.erb
<div class="modal medium-11 medium-centered columns">
  <h4 class="text-center">About the Berkeley Public Schools Fund</h4>
  <p class="text-justify">The Berkeley Public Schools Fund is the single organization that provides classroom grants in addition to other school and Districtwide program funding for every Berkeley public school, from pre-K to 12th grade. Our mission is to inspire and empower an extraordinary public education for every child. Find out more about us on our website.</p>
  <h4 class="text-center">About Friends and Family Grants</h4>
  <p class="text-justify">The Schools Fund Friends & Family Grants Platform is a “crowdfunding” site separate from any current Schools Fund grant-making process. Grants are funded by community donations. The purpose of the platform is to offer teachers a year-round opportunity to have classroom materials and projects funded. Grant requests on this site have been reviewed and approved by the Berkeley Public Schools Fund. Donations will be administered by the Berkeley Public Schools Fund, a 501(c)(3) organization. All donations made are tax deductible to the full extent of the law, less benefits received. Donors will receive an email receipt for tax records. Donations are anonymous.</p>
  <h4 class="text-center">Please submit any feedback or questions about how to use this site using the Contact button at the top of the page.</h4>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_collapsedfooter.html.erb
<div class="footer hide-for-medium">
  <div class="row">
    <div class="medium-2 small-12 columns">
      <h5>Explore</h5>
      <p><%= link_to "Home", root_path %></p>
      <p><a data-open="aboutModal">About Us</a></p>
      <p><%= link_to "Volunteer", "https://www.berkeleypublicschoolsfund.org/volunteer/" %></p>
      <hr>
    </div>
    <div class="medium-2 small-12 columns">
      <h5>Account</h5>
      <p><%= link_to "Sign In", new_user_session_path %></p>
      <p><%= link_to "Sign Up", new_user_registration_path %></p>
      <hr>
    </div>
    <div class="medium-2 small-12 columns">
      <h5>Contact</h5>
      <p><a href="mailto:schoolsfund@berkeley.net">schoolsfund@berkeley.net</a></p>
      <p>510-644-6244</p>
      <p><%= link_to "Facebook", "https://www.facebook.com/berkeleypublicschoolsfund/" %></p>
      <hr>
    </div>
    <div class="large-5 large-offset-1 medium-4 medium-offset-2 small-12 columns">
      <p>All grants have been reviewed and approved by the Berkeley Public Schools Fund</p>
    </div>
  </div>
</div>

app/views/shared/_collapsednavbar.html.erb
<div class="title-bar hide-for-medium" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
  <a class="text-center menu-button" data-toggle><span class="menu-icon "></span><span class="title-bar-title ">Menu</span></a>
  
</div>

<div class="top-bar hide-for-medium" id="example-animated-menu" data-animate="fade-in fade-out">
  <div class="top-bar-left">
    <ul class="vertical dropdown menu" data-dropdown-menu>
      <li class="dropdown-li">
        <%= link_to grants_path do %>
          <h2><%= fa_icon "file-text-o", class:"float-left" %><span class="main-links float-center">Grants</span></h2>
        <% end %>
      </li>
      <li class="dropdown-li">
        <a data-open="aboutModal">
          <h2><%= fa_icon "users", class:"float-left"  %><span class="main-links float-center"  href="#">About Us</span></h2>
        </a>
        <div class="reveal" id="aboutModal" data-reveal>
          <%= render 'shared/about' %>
        </div>
      </li>
      <li class="dropdown-li">
        <a data-open="teacherModal">
          <h2><%= fa_icon "question-circle-o", class:"float-left"  %><span class="main-links float-center">For Teachers</span></h2>
        </a>
        <div class="reveal" id="teacherModal" data-reveal>
          <%= render 'shared/for_teachers' %>
        </div>
      </li>
      <li class="dropdown-li">
        <a data-open="friendModal">
          <h2><%= fa_icon "question-circle-o", class:"float-left"  %><span class="main-links float-center">For Friends and Family</span></h2>
        </a>
        <div class="reveal" id="friendModal" data-reveal>
          <%= render 'shared/for_friends_and_family' %>
        </div>
      </li>
      <li class="dropdown-li">
        <%= link_to new_contact_form_path do %>
          <h2><%= fa_icon "envelope-o", class:"float-left"  %><span class="main-links float-center">Contact</span></h2>
        <% end %>
      </li>
      <li class="dropdown-li">
        <a href="#">
          <h2><%= fa_icon "user-o", class:"float-left" %><span class="main-links float-center">Account</span></h2>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_createbutton.html.erb
<% if current_user and current_user.role == "teacher" %>
  <li><a class="dropdown-links align-center"  href="<%= new_grant_path %>">Create New</a></li>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="small-2 columns">
      <h5>Explore</h5>
      <p>Home</p>
      <p>volunteer</p>
    </div>
    <div class="small-2 columns">
      <h5>Account</h5>
      <p>Sign in</p>
      <p>Sign up</p>
    </div>
    <div class="small-2 columns">
      <h5>Contact</h5>
      <p>schoolsfund@berkeley.net</p>
      <p>510-644-6244</p>
      <p>facebook</p>
    </div>
    <div class="small-5 columns">
      <p>All grants have been reviewed and approved by the Berkeley Public Schools Fund</p>
    </div>
  </div>
</div>

app/views/shared/_for_friends_and_family.html.erb
<div class="modal medium-11 medium-centered columns">
    <h4 class="text-center">FOR FRIENDS AND FAMILY</h4>
    <p class="text-justify"> 1. Sign up and create your account.</p>
    <p class="text-justify"> 2. Find the grant you are interested in by viewing the homepage, searching by teacher, school or subject, or use the direct link to a grant.</p>
    <p class="text-justify"> 3. Make a donation to the grant project you would like to support using a credit card.*</p>
    <p class="text-justify"> 4. Administrative costs of 9% are included in the total cost for the grant.</p>
    <p class="text-justify"> 5. Consider making an additional donation to the Berkeley Public Schools Fund, supporting our school volunteers program and our larger Districtwide and Program Grants.</p>
    <p class="text-justify"> 6. You will receive an email receipt for tax records. All donations made are tax deductible to the full extent of the law, less benefits received. Donations are anonymous.</p>
    <p class="text-justify"> 7. Share this project with your friends, family and social networks to increase funding sources for the grant project.</p>
    <p class="text-justify"> * Your donation is a “pledge”. Your credit card will not be charged until the project is fully pledged. The application holds an encrypted token that is sent to the credit card processing service and held until the grant is fully pledged. At that time, your credit card will be charged.</p>
    <h4 class="text-center">Please submit any feedback or questions about how to use this site using the Contact button at the top of the page.</h4>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/shared/_for_teachers.html.erb
<div class="modal medium-11 medium-centered columns">
    <h4 class="text-center">FOR TEACHERS</h4>
    <p class="text-justify"> 1.  Sign up and create your account.</p>
    <p class="text-justify"> 2.  Log in and click “Apply for Grant”</p>
    <p class="text-justify"> 3.  Complete the brief online application. You can save and return to your application using your account login at any time. Please provide a project budget that is specific and accurate, and please set a reasonable timeline for raising the funds on the Friends & Family site.</p>
    <p class="text-justify"> 4.  Friends & Family grant funds cannot be used to pay an independent consultant (non-profit organizations are okay).</p>
    <p class="text-justify"> 5.  The Schools Fund will review your grant application and provide you with a response within a week of your submission. Approval will be based on a well-justified explanation of the educational value of the project.</p>
    <p class="text-justify"> 6.  If your grant application is approved, you will receive a notification email with a project link from the Berkeley Public Schools Fund, including sample text for you to send to your class/contact list. The grant amount that you applied for will have a 9% administration fee added to it when we post it to the site ($50 grant will become $54.50).</p>
    <p class="text-justify"> 7.  Email the grant link to your classroom parents and other contacts. Share this project with your friends, family and social networks to increase funding sources for your grant project.</p>
    <p class="text-justify"> 8.  Your grant will be visible and searchable (under your name, school or grant subject) on the Schools Fund Friends & Family site. The Schools Fund will also help promote grant projects through our monthly e-Newsletter and Facebook page.</p>
    <p class="text-justify"> 9.  Once you have received full funding for your grant, the Schools Fund will send you a check for the requested amount in your application.</p>
    <p class="text-justify"> 10.  Please send all receipts to the Schools Fund within 90 days of receiving funding. Failure to provide receipts may affect your ability to receive future grants.</p>
    <p class="text-justify">  11.  There is no limit to how frequently you apply for grants on the Friends & Family site.</p>
    <h4 class="text-center">Thank you for all of your hard work. We hope you find this site helpful!</h4>
    <h4 class="text-center">Please submit any feedback or questions about how to use this site using the Contact button at the top of the page.</h4>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/shared/_fullfooter.html.erb
<div class="footer show-for-medium">
  <div class="row">
    <div class="medium-2 small-12 columns">
      <h5>Explore</h5>
      <p><%= link_to "Home", root_path %></p>
      <p><a data-open="aboutModal">About Us</a></p>
      <p><%= link_to "Volunteer", "https://www.berkeleypublicschoolsfund.org/volunteer/" %></p>
    </div>
    <div class="medium-2 small-12 columns">
      <h5>Account</h5>
      <p><%= link_to "Sign In", new_user_session_path %></p>
      <p><%= link_to "Sign Up", new_user_registration_path %></p>
    </div>
    <div class="medium-2 small-12 columns">
      <h5>Contact</h5>
      <p><a href="mailto:schoolsfund@berkeley.net">schoolsfund@berkeley.net</a></p>
      <p style="white-space: nowrap;">510-644-6244</p>
      <p><%= link_to "Facebook", "https://www.facebook.com/berkeleypublicschoolsfund/" %></p>
    </div>
    <div class="large-4 large-offset-2 medium-3 medium-offset-3 small-12 columns">
      <p>All grants have been reviewed and approved by the Berkeley Public Schools Fund</p>
    </div>
  </div>
</div>

app/views/shared/_fullnavbar.html.erb
<div class="nav show-for-medium">
  <ul class="dropdown menu expanded" data-dropdown-menu data-closing-time="50">
    <% if current_user && current_user.role != "friends_and_family" %>
    <li class="menu-item">
      <a class="main-links align-center">
        <h1><%= fa_icon "file-text-o", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">Grants</h6>
      </a>

      <ul class="menu">
        <li><%= link_to "View Grants", grants_path, class: "dropdown-links align-center" %></li>
        <% if current_user && current_user.role == "teacher" %>
          <li><%= link_to "Your Grants", user_grants_path, class: "dropdown-links align-center" %></li>
        <% end %>
        <li><%= link_to "Apply", new_grant_path, class: "dropdown-links align-center" %></li>
      </ul>

    </li>


    <% else %>
    <li class="menu-item">
      <%= link_to grants_path do %>
        <h1><%= fa_icon "file-text-o", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">Grants</h6>
      <% end %>
    </li>
    <% end %>

    <li class="menu-item">
      <a class="main-links align-center" data-open="aboutModal">
        <h1><%= fa_icon "users", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">About Us</h6>
      </a>
      <div class="reveal" id="aboutModal" data-reveal>
        <%= render 'shared/about' %>
      </div>
    </li>

    <li class="menu-item">
      <a class="main-links align-center">
        <h1><%= fa_icon "question-circle-o", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">FAQ</h6>
      </a>
      <ul class="menu">

        <!-- For teachers modal -->
        <li><a class="dropdown-links align-center" data-open="teacherModal">For Teachers</a></li>
        <div class="reveal" id="teacherModal" data-reveal>
          <%= render 'shared/for_teachers' %>
        </div>

        <!-- For friends and Families modal -->
        <li><a class="dropdown-links align-center" data-open="friendModal" >For Friends and Family</a></li>
        <div class="reveal" id="friendModal" data-reveal>
          <%= render 'shared/for_friends_and_family' %>
        </div>
      </ul>
    </li>

    <li class="menu-item">
      <%= link_to new_contact_form_path do %>
        <h1><%= fa_icon "envelope-o", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">Contact<h6>
      <% end %>
    </li>


    <li class="menu-item">
      <a class="main-links align-center">
        <h1><%= fa_icon "user-o", class: "icon-in-menu" %></h1>
        <h6 class="main-links align-center">Account</h6>
      </a>

      <ul class="menu">
        <% if current_admin_user %>
          <li><%= link_to "Admin Dashboard", admin_root_path, class: "dropdown-links align-center" %></li>
        <% end %>
        <% if !current_user %>
          <li><%= link_to "Sign In", new_user_session_path, class: "dropdown-links align-center" %></li>
          <li><%= link_to "Register", new_user_registration_path, class: "dropdown-links align-center" %></li>
        <% else %>
          <li><%= link_to "Dashboard", user_path, method: "get", class: "dropdown-links align-center" %></li>
          <% if current_user.role == "teacher" %>
            <li><%= link_to "Your Grants", user_grants_path, class: "dropdown-links align-center" %></li>
          <% end %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "dropdown-links align-center" %></li>
        <% end %>
      </ul>

    </li>

  </ul>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <a href="/">
    <%= image_tag image_path("ctahead.png"), class: "friends-banner" %>
  </a>
</div>