config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => { :registrations => "custom/registrations" }

  match '/contact_forms/new', to: 'contact_forms#new', via: 'get'
  resources "contact_forms", only: [:new, :create]
  root to: "home#index"

  resource :user, only: [:show] do
    resource :profiles, path: "profile", except: [:index, :show, :delete]
  end

  get '/users', to: redirect('/users/sign_up')

  get '/user/grants', to: 'grants#usergrants', as: 'user_grants'

  post '/user/card', to: 'users#create_card', as: 'create_card'

  delete '/user/card', to: 'users#delete_card', as: 'delete_card'

  post '/user/card/edit', to: 'users#edit_card', as: 'edit_card'

  resources :grants do
    resources :payments, except: [:index]
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :grant

  enum status: { "pending" => 0, "charged" => 1, "cancelled" => 2 }

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :authenticate_user!
  before_action :has_profile?
  before_action :stripe_token_and_no_card?, only: :new
  before_action :set_payment, only: :destroy
  before_action :owner_or_admin?, only: :destroy
  before_action :set_next

  def new
    @grant = Grant.find(params[:grant_id])
    @payment = Payment.new
    update_profile?
  end

  def create
    if !current_user.stripe_token?
      Stripe.api_key = ENV["stripe_api_key"]
      customer = Stripe::Customer.create({
        description: "Customer for #{current_user.first_name} #{current_user.last_name}",
        source: params[:stripeToken]
        })
      current_user.stripe_token = customer.id
      current_user.save
    end
    #grant before adding new payment
    oldgrant = Grant.find(params[:grant_id])
    total = oldgrant.amount_raised
    @payment = Payment.new
    @payment.user = current_user
    @payment.grant = Grant.find(params[:grant_id])
    @payment.amount = params[:amount]
    @payment.pending!
    @admins = AdminUser.all
    #grant after adding new payment
    grant = Grant.find(params[:grant_id])
    #Check amount raised and send mailer if grant is funded or near funded
    if @payment.save
      UserPledgeJob.new.async.perform(@payment.user, grant, @payment)
      grant.check_total(total, @admins, @payment)
      redirect_to grant_path(@payment.grant), notice: "You have successfully pledged $#{@payment.amount}!"
    else
      render :new
    end
  end

  def destroy
    @payment.destroy
    redirect_to grants_url, notice: 'Payment was successfully destroyed.'
  end

  private

  def has_profile?
    unless current_admin_user or (current_user and current_user.profile)
      session[:next] = "#{request.original_fullpath}"
      redirect_to new_user_profiles_path, alert: "Please create a profile first."
    end
  end

  def payment_params
    params.permit(:amount, :grant_id, :stripeToken)
  end

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def owner_or_admin?
    redirect_to grants_path unless @payment.user == current_user or current_admin_user
  end

  def stripe_token_and_no_card?
    if current_user and current_user.stripe_token?
      Stripe.api_key = ENV['stripe_api_key']
      customer = Stripe::Customer.retrieve(current_user.stripe_token)
      unless customer.sources.total_count > 0
        session[:next] = "#{request.original_fullpath}"
        redirect_to user_path + "?current=credit-card-label", alert: 'Add a new credit card before donating'
      end
    end
  end

  def update_profile?
    # Update profile if you are coming from clicking the donate button on grant show page
    if request.base_url + grant_path(@grant) == request.referer
      flash[:info] = "Please confirm the information below before donating."
      session[:next] = "#{request.original_fullpath}"
      redirect_to edit_user_profiles_path
    end
  end

  def set_next
    @next = session[:next] if session[:next]
    session[:next] = nil
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_customer_form.html.erb
<%= form_tag grant_payments_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
  <div class="input-group">
    <%= label_tag(:amount, '$USD:', class: "input-group-label") %>
    <%= text_field_tag :amount, "", class: "input-group-field" %>
    <div class="input-group-button">
      <% if current_user and current_user.stripe_token? %>
        <input type="submit" class="button warning donation" value="Donate">
      <% else %>
        <%= hidden_field_tag(:stripeToken) %>
        <button id='donateButton', class="button warning donation">Donate</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/payments/_returning_customer_form.html.erb
<%= form_tag grant_payments_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
    <% end %>
  </div>
  <div class="input-group">
    <%= label_tag(:amount, '$USD:', class: "input-group-label") %>
    <%= text_field_tag :amount, "", class: "input-group-field" %>
    <div class="input-group-button">
      <input type="submit" class="button warning donation" value="Donate">
    </div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Edit Donation</h1>

<%= render "form" %>

app/views/payments/new.html.erb
<h1 class="text-center warning-color">New Donation</h1>
<hr>

<div class="grant-container show-for-medium">
  <%= render "/grants/grantspartial", grant: @grant %>
</div>
<div class="grant-container hide-for-medium">
  <%= render "/grants/grantscard", grant: @grant %>
</div>
<div class="columns small-12 medium-6 medium-offset-3">
  <%= render "customer_form" %>
</div>
<br>