config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => { :registrations => "custom/registrations" }

  match '/contact_forms/new', to: 'contact_forms#new', via: 'get'
  resources "contact_forms", only: [:new, :create]
  root to: "home#index"

  resource :user, only: [:show] do
    resource :profiles, path: "profile", except: [:index, :show, :delete]
  end

  get '/users', to: redirect('/users/sign_up')

  get '/user/grants', to: 'grants#usergrants', as: 'user_grants'

  post '/user/card', to: 'users#create_card', as: 'create_card'

  delete '/user/card', to: 'users#delete_card', as: 'delete_card'

  post '/user/card/edit', to: 'users#edit_card', as: 'edit_card'

  resources :grants do
    resources :payments, except: [:index]
  end

end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :school
  has_many :payments, dependent: :destroy
  mount_uploader :image, ImageUploader

  enum status: { "draft" => 0, "pending" => 1, "approved" => 2, "rejected" => 3, "failed" => 4, "successful" =>5}

  def subject_areas_options
    [nil,'After School Program', 'Arts / Music', 'Arts / Dance', 'Arts / Drama',
      'Arts / Visual', 'Community Service', 'Computer / Media', 'Computer Science',
      'Foreign Language / ELL / TWI','Gardening','History & Social Studies / Multi-culturalism',
      'Mathematics','Multi-subject','Nutrition','Physical Education', 'Reading & Writing / Communication',
      'Science & Ecology','Special Ed','Student / Family Support / Mental Health']
  end

  def funds_will_pay_for_options
    [nil,'Supplies','Books','Equipment','Technology / Media',
      'Professional Guest (Consultant, Speaker, Artist, etc.)','Professional Development',
      'Field Trips / Transportation','Assembly']
  end

  validate :state_transition, on: :save
  validates :user, :school, :status, presence: true

  def percent_complete
    percent = ([self.amount_raised/self.with_admin_cost.to_f, 1].min * 100).to_i
    percent
  end

  def progress
    if self.total_budget
      "#{self.percent_complete}%"
    else
      ""
    end
  end

  def amount_raised
    total = 0
    self.payments.each do |payment|
      total += payment.amount
    end
    total
  end

  def days_left
    (self.deadline - Time.now.getlocal("-07:00").to_date).to_i
  end

  def past_deadline?
    days_left <= 0
  end

  def crowdfailed
    @admins = SuperUser.all
    # @admins.each do |admin|
    #   AdminCrowdfailedJob.new.async.perform(self, admin)
    # end
    GrantCrowdfailedJob.new.async.perform(self)
  end

  def check_total(total, admins, payment)
    if total < self.with_admin_cost && total + payment.amount >= self.with_admin_cost
      admins.each do |admin|
        AdminCrowdsuccessJob.new.async.perform(self, admin)
      end
      users_notified = []
      self.payments.all.each do |userpayment|
        if !users_notified.include?(userpayment.user)
          UserCrowdsuccessJob.new.async.perform(userpayment.user, self)
          users_notified.push(userpayment.user)
        end
      end
      GrantFundedJob.new.async.perform(self)
    elsif self.amount_raised >= (self.with_admin_cost * 0.8) && (self.amount_raised < self.with_admin_cost)
      DonorNearendJob.new.async.perform(self, payment.user)
    end
  end

  def display_status
    if self.status == "draft"
      return "Draft Grant"
    elsif self.status == "pending"
      return "Pending Approval"
    elsif self.status == "approved"
      return "Currently Crowdfunding"
    elsif self.status == "rejected"
      return "Rejected Grant"
    elsif self.status == "successful"
      return "Successfully Funded"
    elsif self.status == "failed"
      return "Failed To Reach Goal"
    end
  end

  def with_admin_cost
    # 9% cost added
    if self.total_budget
      (self.total_budget * 1.09).to_i
    else
      ""
    end
  end

  def admin_cost
    if self.total_budget
      self.with_admin_cost - self.total_budget
    else
      ""
    end
  end


  def state_transition(status)
    if      self.draft?     &&  ["pending"].include?(status)
      return true
    elsif   self.pending?   &&  ["draft", "rejected", "approved"].include?(status)
      return true
    elsif   self.approved?  &&  ["failed", "successful"].include?(status)
      return true
    elsif   self.status == status
      return true
    else
      errors.add(:status, "That state transition is not possible.")
      return false
    end
  end

  

end

app/controllers/grants_controller.rb
# t.text     "title"
# t.text     "summary"
# t.integer  "subject_areas"
# t.text     "grade_level"
# t.text     "duration"
# t.integer  "num_classes"
# t.integer  "num_students"
# t.integer  "total_budget"
# t.integer  "funds_will_pay_for"
# t.text     "budget_desc"
# t.text     "purpose"
# t.text     "methods"
# t.text     "background"
# t.integer  "num_collabs"
# t.text     "collaborators"
# t.text     "comments"
# t.integer  "user_id"
# t.string   "state"
# t.string   "video"
# t.string   "image"
# t.integer  "school_id"
# t.integer  "status"
# t.date     "deadline"
# t.datetime "created_at",         null: false
# t.datetime "updated_at",         null: false
# t.index ["school_id"], name: "index_grants_on_school_id", using: :btree
# t.index ["user_id"], name: "index_grants_on_user_id", using: :btree

# enum status: { "draft" => 0, "pending" => 1, "approved" => 2, "rejected" => 3, "failed" => 4, "successful" =>5}
#
# enum subject_areas: ['After School Program', 'Arts / Music', 'Arts / Dance', 'Arts / Drama',
#   'Arts / Visual', 'Community Service', 'Computer / Media', 'Computer Science',
#   'Foreign Language / ELL / TWI','Gardening','History & Social Studies / Multi-culturalism',
#   'Mathematics','Multi-subject','Nutrition','Physical Education', 'Reading & Writing / Communication','Science & Ecology',
#   'Special Ed','Student / Family Support / Mental Health']
#
# enum funds_will_pay_for: ['Supplies','Books','Equipment','Technology / Media',
#   'Professional Guest (Consultant, Speaker, Artist, etc.)','Professional Development',
#   'Field Trips / Transportation','Assembly']

class GrantsController < ApplicationController
  before_action :permission, except: [:index, :show]
  before_action :set_grant, only: [:show, :edit, :update, :destroy]
  before_action :owner, only: [:edit, :update, :destroy]
  before_action :already_submitted, only: [:edit, :update]
  before_action :has_profile?, except: [:index, :usergrants, :show]
  before_action :set_next

  # GET /grants
  def index
    @school = School.all
    @grants = Grant.where("status = '2' OR status = '5'").paginate(page: params[:page], per_page: 5).order(deadline: :asc)
    if params[:filter] && params[:filter] != "All" && [ 'approved', 'successful'].include?(params[:filter])
      @grants = Grant.where(status: params[:filter]).paginate(page: params[:page], per_page: 5).order(deadline: :asc)
    end
    if params[:school_id] && params[:school_id] != ""
      @grants = @grants.where(school_id: params[:school_id]).paginate(page: params[:page], per_page: 5).order(deadline: :asc)
    end
    if params[:teacher] && params[:teacher] != ""
      @grants = @grants.joins(:user).where(users: {last_name: params[:teacher].capitalize}).paginate(page: params[:page], per_page: 5).order(deadline: :asc)
    end
  end

  # GET user/grants
  def usergrants
    if params[:filter] && params[:filter] != "all" && ['draft', 'pending', 'rejected', 'approved', 'failed', 'successful'].include?(params[:filter])
      @grants = current_user.grants.where(status: params[:filter]).paginate(page: params[:page], per_page: 10).order(deadline: :asc)
      @filter = params[:filter]
    else
      @grants = current_user.grants.where(status: [:draft, :pending, :rejected, :approved, :failed, :successful]).paginate(page: params[:page], per_page: 5).order(deadline: :asc)
    end
  end

  # GET /grants/1
  def show
    if @grant.video != ""
      youtubeId = @grant.video.match(/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/ ]{11})/i)
      if youtubeId
        @embed = "https://www.youtube.com/embed/#{youtubeId[1]}"
      end
    end
  end

  # GET /grants/new
  def new
    @grant = Grant.new
  end

  # GET /grants/1/edit
  def edit
  end

  # POST /grants
  def create
    parameters = grant_params
    if params[:file]
      parameters[:image] = params[:file]
    end
    @grant = Grant.new(parameters)
    @grant.user = current_user
    @grant.school = School.find(current_user.school_id)
    @admins = AdminUser.all
    if @grant.save
      if grant_params[:status] == "pending"
        @admins.each do |admin|
          AdminGrantsubmittedJob.new.async.perform(@grant, admin)
        end
        GrantSubmittedJob.new.async.perform(Grant.last)
      end
      redirect_to @grant, notice: 'Grant was successfully created.'
    else
      render :new
    end
  end


  # PATCH/PUT /grants/1
  def update
    @admins = AdminUser.all
    parameters = grant_params
    if params[:file]
      parameters[:image] = params[:file]
    end
    if @grant.update(parameters)
      if @grant.status != grant_params[:status]
        status_change
      end
      redirect_to @grant, notice: 'Grant was successfully updated.'
    else
      redirect_to @grant, alert: 'Could not update grant'
    end
  end

  # DELETE /grants/1
  def destroy
    @grant.destroy
    redirect_to grants_url, notice: 'Grant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grant
      if !Grant.exists?(params[:id])
        redirect_to grants_path
      else
        @grant = Grant.find(params[:id])
      end
    end

    def status_change
      if @grant.draft? && grant_params[:status] == "pending"
        GrantSubmittedJob.new.async.perform(@grant)
      end
      if !@grant.state_transition(grant_params[:status])
        render :edit, alert: 'That is not a valid state transition'
      elsif @grant.update(grant_params)
        if grant_params[:status] == "draft"
        redirect_to @grant, notice: 'Grant was successfully updated.'
        elsif grant_params[:status] == "pending"
        redirect_to @grant, notice: 'Grant was successfully submitted.'
        end
      else
        render :edit
      end
    end

    # Only allow a trusted parameter "white list" through.
    def grant_params
      params.require(:grant).permit(:title, :summary, :subject_areas, :grade_level,
                                    :duration, :num_classes, :num_students,
                                    :total_budget, :funds_will_pay_for, :budget_desc,
                                    :purpose, :methods, :background, :num_collabs,
                                    :collaborators, :comments, :user_id, :state,
                                    :video, :school_id, :status, :deadline)
    end

    def permission
      redirect_to grants_path unless ((current_user and current_user.role == "teacher") or current_admin_user)
    end

    def owner
      redirect_to grant_path(@grant), alert: "Don't have required permissions" unless (@grant.user == current_user || current_admin_user)
    end

    def already_submitted
      redirect_to grant_path(@grant), alert: "Grant has already been submitted" unless (@grant.draft? || current_admin_user)
    end

    def has_profile?
      redirect_to new_user_profiles_path + "?next=#{request.original_fullpath}", alert: "Please create a profile first." unless current_admin_user or (current_user and current_user.profile)
    end

    def set_next
      @next = session[:next] if session[:next]
      session[:next] = nil
    end

end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/grants/_form.html.erb
<div id="blur-div">
  <div id="crop-contain">
    <img src="#" id="grant-img-preview">
  </div>
  <button class="succes button crop-img">Save</button>
</div>
<%= simple_form_for @grant, html: {multipart: true} do |f| %>
  <%= f.error_notification %>
  <img src="#" class="final-crop">
  <div class="form-inputs">
    <%= f.input :image %>
    <%= f.input :title, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Name your grant. A good title summarizes the essence of the application." }, required: true %>
    <%= f.input :summary, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Give a brief explanation of your application (200 word limit)" }, required: true %>
    <%= f.input :subject_areas, input_html: { tabindex: -1 }, required: true, wrapper_html: {:class => "invis"} %>
    <label class="text"><abbr>*</abbr> Subject areas</label>
    <% if @grant.subject_areas %>
      <% @grant.subject_areas.split(", ").each do |subject| %>
        <p class="subject-option"><%= subject %> <i class="fa fa-times"></i></p>
      <% end %>
    <% end %>
    <%= select_tag :subject_options, options_for_select(@grant.subject_areas_options), class: "inputs" %>
    <%= f.input :grade_level, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "List the grade levels that will be affected. Please separate different grades by commas." }, required: true %>
    <%= f.input :duration, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "How long will the proposed activity last? Please enter a number followed by a time period (ex. 1 day, 2 weeks, 3 months). If this is not applicable then please put 'n/a'." }, required: true %>
    <%= f.input :num_classes, :label => "Number of classes",  input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "How many different classes will be affected by the application?" }, required: true %>
    <%= f.input :num_students, :label => "Number of students", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "How many students will be affected by the application?" }, required: true %>
    <%= f.input :total_budget, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Enter total $ amount of your budget" }, required: true %>
    <%= f.input :funds_will_pay_for, input_html: { tabindex: -1 }, required: true, wrapper_html: {:class => "invis"} %>
    <label class="text"><abbr>*</abbr> Funds will pay for</label>
    <% if @grant.funds_will_pay_for %>
      <% @grant.funds_will_pay_for.split(", ").each do |fund| %>
        <p class="fund-option"><%= fund %> <i class="fa fa-times"></i></p>
      <% end %>
    <% end %>
    <%= select_tag :fund_options, options_for_select(@grant.funds_will_pay_for_options), class: "inputs" %>
    <%= f.input :budget_desc, :label => "Budget description", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Explain in specific detail how the budget will be allotted and used." }, required: true %>
    <%= f.input :purpose, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "What is the purpose of this grant request and proposal?" }, required: true %>
    <%= f.input :methods, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "What methods will you employ in the implementation of this plan? Basically, what is your implementation strategy?" }, required: true %>
    <%= f.input :background, :label => "Teacher background", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "What is your own background? Please explain any relevant details to yourself and the project." }, required: true %>
    <%= f.input :num_collabs, :label => "Number of collaborators", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Not including yourself, how many people are collaborating on this application?" }, required: true %>
    <%= f.input :collaborators, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Please list all the people with whom you will collaborate, if any, and what role they will play." }, required: true %>
    <%= f.input :comments, :label => "Other comments", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Please state any additional information that may contribute to your application." } %>
    <%= f.input :video, :label => "Youtube video", input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "Link to a Youtube Video about your grant." } %>
    <%= f.input :deadline, input_html: { "data-tooltip" => true, "data-disable-hover" => true, :class => "has-tip inputs", :title => "When will your crowdfunding period end?" }, required: true %>
    <%= f.hidden_field :status, value: "pending", id: "status" %>
  </div>

    <%= f.button :submit, class: 'hide', id: "new-grant" %>
    <a href="<%= grants_path %>"><button type="button" name="button" class="button primary hollow">Back</button></a>
    <button type="button" name="button" id="submit" class="button float-right warning hollow"><strong>Submit</strong></button>
    <button type="button" name="button" id="draft" class="button float-right secondary hollow"><strong>Save as Draft</strong></button>
<% end %>

app/views/grants/_grantscard.html.erb
<%= link_to grant_path(grant), class: "grant-row-partial" do %>
  <div class="card grant-row row">
    <%= cl_image_tag(grant.image, class: "grant-partial-image float-center")%>
    <div class="columns medium-6 large-8 small-12">
      <h3 class="text-center hover-orange"><%= grant.title %></h3>
      <p class="text-center"><%= grant.user.first_name %> <%= grant.user.last_name %></p>
      <p class="text-center"><%= grant.school.name %></p>
      <h6 class="text-justify"><%= grant.summary %></6>
      <h4 class="text-center"><span class="amount">$<%= grant.amount_raised %></span> of $<%= grant.with_admin_cost %>
        <% if grant.days_left > 1 %>
          with <%= pluralize(grant.days_left, 'day') %> left
        <% elsif grant.days_left > 0 %>
          Last day to Donate!
        <% else %>
          <%= grant.status %>
        <% end %>
      </h4>
      <div class="progress" role="progressbar" tabindex="0" aria-valuenow="<%= grant.amount_raised %>" aria-valuemin="0" aria-valuemax="<%= grant.with_admin_cost %>">
        <div class="progress-meter" style="width: <%= grant.progress %>"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/grants/_grantspartial.html.erb
<%= link_to grant_path(grant), class: "grant-row-partial" do %>
  <div class="grant-row row align-middle">
    <div class="columns medium-6 large-4 show-for-medium">
      <%= cl_image_tag(grant.image, class: "grant-partial-image")%>
    </div>
    <div class="columns medium-6 large-8 small-12">
      <h3 class="hover-orange"><%= grant.title %></h3>
      <p><%= grant.user.first_name %> <%= grant.user.last_name %> | <%= grant.school.name %></p>
      <h6><%= grant.summary %></h6>
      <h4><span class="amount">$<%= grant.amount_raised %></span> of $<%= grant.with_admin_cost %>
        <% if grant.days_left > 1 %>
          with <%= pluralize(grant.days_left, 'day') %> left
        <% elsif grant.days_left > 0 %>
          Last day to Donate!
        <% else %>
          <%= grant.status %>
        <% end %>
      </h4>
      <div class="progress" role="progressbar" tabindex="0" aria-valuenow="<%= grant.amount_raised %>" aria-valuemin="0" aria-valuemax="<%= grant.with_admin_cost %>">
        <div class="progress-meter" style="width: <%= grant.progress %>"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/grants/edit.html.erb
<h1>Editing Grant</h1>
<%= render 'form', grant: @grant %>

<%= link_to 'Show', @grant %> |
<%= link_to 'Back', grants_path %>

app/views/grants/index.html.erb
<h4>Filter by:</h4>
<%= form_tag(grants_path, :method => "get", enforce_utf8: false, id: "filter-form") do %>
  <div class = "row">
    <div class="medium-3 columns">
      <%= label_tag :filter, "Status" %>
      <%= select_tag :filter, options_for_select({All: 1, Crowdfunding: "approved", Successful: "successful"}, params[:filter] ), id: "filter-select" %>
    </div>
    <div class="medium-3 columns">
      <%= label_tag :school_id, "School" %>
      <%= select_tag :school_id, options_from_collection_for_select(@school, "id", "name", params[:school_id]), id: "school-select", include_blank: "All" %>
    </div>
      <div class="medium-3 columns">
      <%= label_tag :teacher, "Teacher's last name" %>
      <%= text_field_tag :teacher, params[:teacher], placeholder: "Teacher's last name" %>
    </div>
    <div class="medium-3 columns">
      <%= submit_tag "Apply filters", class: "button warning", style: "transform: translateY(50%)" %>
    </div>
  </div>
<% end %>
<hr>

<% unless @grants.empty? %>
  <div class="grant-container show-for-medium">
    <% @grants.each do |grant| %>
      <%= render "grantspartial", grant: grant %>
    <% end %>
  </div>
  <div class="grant-container hide-for-medium">
    <% @grants.each do |grant| %>
      <%= render "grantscard", grant: grant %>
    <% end %>
  </div>
  <div class="small-12 columns">
    <%= will_paginate @grants, class: "apple_pagination" %>
  </div>
<% else %>
  <br>
  <h4 style="text-align: center;"> No results found</h4>
<% end %>

app/views/grants/new.html.erb
<h1>New Grant</h1>

<%= render "form" %>

app/views/grants/show.html.erb
<%= content_for :title, @grant.title %> 
<div class="row">
  <div class="columns small-12">
    <span class = "float-left">
      <% if @grant.status == "approved" %>
          <div class="social-icon" data-bp-social='facebook'>
            <a class="fb-button"><i class="fa fa-facebook-square fa-2x"></i></a>
          </div>
          <div class ="social-icon" data-bp-social='twitter'>
            <a class = "tw-button"><i class="fa fa-twitter fa-2x"></i></a>
          </div>
          <div class="social-icon" data-bp-social='mail'>
            <a class="mail-button" href="mailto:?subject=<%= @grant.title %>&body=https://bpsfgrants.herokuapp.com<%= grant_path %>"><i class="fa fa-envelope fa-2x"></i></a>
          </div>
        <% end %>
    </span>
    <h2 class="text-center"><%= @grant.title %>
    </h2>
    <h5 class="text-center">By <%= @grant.user.first_name %> <%= @grant.user.last_name %> at <%= @grant.school.name %></h5>
    <h4 class="text-center"><%= @grant.display_status %></h4>
    <% if (@grant.user == current_user && @grant.draft?) or current_admin_user %>
      <a href="<%= edit_grant_path(@grant) %>" id="edit-button" class="float-center button warning"><%= fa_icon "pencil 2x" %></a>
    <% end %>
    <hr>
  </div>
  
</div>

<div class="row align-middle">
  <div class="columns small-12 medium-6">
    <%= cl_image_tag(@grant.image, class: "text-center")%>
  </div>
  
  <div class="columns small-12 medium-6">
    <h4 class="grant-section-title text-center">Summary</h4>
    <h6 class="text-center"><%= @grant.summary %></h6>
    <hr>
    <h4 class="text-center"><span class="amount">$<%= @grant.amount_raised %></span> of $<%= @grant.with_admin_cost %>
      <% if @grant.days_left > 1 %>
        with <%= pluralize(@grant.days_left, 'day') %> left
      <% elsif @grant.days_left > 0 %>
        Last day to Donate!
      <% else %>
        <%= @grant.status %>
      <% end %>
    </h4>
    <div class="progress" role="progressbar" tabindex="0" aria-valuenow="<%= @grant.amount_raised %>" aria-valuemin="0" aria-valuemax="<%= @grant.with_admin_cost %>">
      <div class="progress-meter" style="width: <%= @grant.progress %>"></div>
    </div>
    <% if @grant.approved? %>
      <%= button_to "Donate!", new_grant_payment_path(@grant), method: "get", class: "button warning large float-center" %>
    <% end %>
  </div>
  <% if @embed %>
    <div class="columns small-12">
    <br>
      <iframe src= <%= @embed %> width="450" height="225" class= "float-center"></iframe>
    </div>
  <% end %>
</div>
<hr>
<div class="row">
  <div class="columns small-12">
    <h3>Description</h3>
  </div>
  <div class="columns medium-12">
    <table class="unstriped stack">
      <tbody>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Purpose:</h5></td>
          <td><p class="grant-content"><%= @grant.purpose %></p></td>
        </tr>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Methods:</h5></td>
          <td><p class="grant-content"><%= @grant.methods %></p></td>
        </tr>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Teacher Background:</h5></td>
          <td><p class="grant-content"><%= @grant.background %></p></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="columns small-12">
    <h3>Details</h3>
  </div>
  <div class="columns medium-8 small-12">
    <table class="unstriped">
      <tbody>
        <tr>
          <td><h5 class="grant-section-title">Grade Level:</h5></td>
          <td><h5 class="grant-content"><%= @grant.grade_level %></h5></td>
        </tr>
        <tr>
          <td><h5 class="grant-section-title">Duration:</h5></td>
          <td><h5 class="grant-content"><%= @grant.duration %></h5></td>
        </tr>
        <tr>
          <td><h5 class="grant-section-title"># of Classes:</h5></td>
          <td><h5 class="grant-content"><%= @grant.num_classes %></h5></td>
        </tr>
        <tr>
          <td><h5 class="grant-section-title"># of Students:</h5></td>
          <td><h5 class="grant-content"><%= @grant.num_students %></h5></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="columns medium-4 small-12">
    <table class="unstriped">
      <tbody>
        <tr>
          <td><h5 class="grant-section-title">Collaborators:</h5></td>
        </tr>
        <tr>
          <td><p><%= @grant.collaborators %></p></td>
        </tr>
        <tr>
          <td><h5 class="grant-section-title">Subject Areas:</h5></td>
        </tr>
        <tr>
          <td><p><%= @grant.subject_areas %></p></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="columns small-12">
    <h3>Allocation</h3>
  </div>
  <div class="columns medium-12">
    <table class="unstriped stack">
      <tbody>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Budget:</h5></td>
          <td><p class="grant-content">$<%= @grant.total_budget %> (does not include 9% administrative and credit card processing fee)</p></td>
        </tr>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Description:</h5></td>
          <td><p class="grant-content"><%= @grant.budget_desc %></p></td>
        </tr>
        <tr>
          <td valign="top"><h5 class="grant-section-title">Use of Funds:</h5></td>
          <td><p class="grant-content"><%= @grant.funds_will_pay_for %></p></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="columns small-12">
    <h3>Additional Comments:</h3>
  </div>
  <div class="columns medium-12">
    <p class="grant-content"><%= @grant.comments %></p>
  </div>
</div>

app/views/grants/usergrants.html.erb
<%= form_tag(user_grants_path, :method => "get", enforce_utf8: false, id: "filter-form") do %>
  <%= select_tag :filter, options_for_select({All: "all", Draft: "draft", Submitted: "pending", Rejected: "rejected", Funding: "approved", Failed: "failed", Successful: "successful"}, @filter), id: "filter-select" %>
<% end %>
<div class="grant-container show-for-medium">
  <% @grants.each do |grant| %>
    <%= render "grantspartial", grant: grant %>
  <% end %>
</div>
<div class="grant-container hide-for-medium">
  <% @grants.each do |grant| %>
    <%= render "grantscard", grant: grant %>
  <% end %>
</div>
<div class="small-12 columns">
  <%= will_paginate @grants, class: "apple_pagination" %>
</div>